import { defaultModelName, findModelPricing } from "../config/models.js";
import { calculateEstimatedCost, estimateTokensFromText } from "../metrics/tokenEstimator.js";
import type { LLMClient, LLMResponse, ModelPricing } from "../types.js";

const MOCK_OUTPUT = `let mocha = require('mocha');
let assert = require('assert');

describe('mock generated test', function() {
  it('returns a placeholder test generated by MockLLMClient', function(done) {
    assert.ok(true);
    done();
  });
});`;

export class MockLLMClient implements LLMClient {
  private readonly modelName: string;
  private readonly modelPricing?: ModelPricing;

  constructor(modelName = `mock-${defaultModelName}`) {
    this.modelName = modelName;
    this.modelPricing = findModelPricing(defaultModelName);
  }

  async generate(prompt: string): Promise<LLMResponse> {
    const startedAt = Date.now();
    const inputTokens = estimateTokensFromText(prompt);
    const outputTokens = estimateTokensFromText(MOCK_OUTPUT);
    const estimatedCost = this.modelPricing
      ? calculateEstimatedCost(inputTokens, outputTokens, this.modelPricing)
      : 0;

    return {
      text: MOCK_OUTPUT,
      provider: "mock",
      model: this.modelName,
      inputTokens,
      outputTokens,
      totalTokens: inputTokens + outputTokens,
      estimatedCost,
      latencyMs: Date.now() - startedAt,
      rawResponse: {
        note: "No external LLM call was made."
      }
    };
  }
}
